import type { SourceManifestResponse } from "../api/upload";

// Generated by `scripts/generate-source-manifest-static.mjs` from
// `creator_optimizer.workspace_data_sources.build_source_manifest_payload()`.
// Do not hand-edit this file.
// Generated from creator_optimizer commit: 679b8d2
export const STATIC_SOURCE_MANIFEST_RESPONSE: SourceManifestResponse = {
  "version": 1,
  "eligibility_rule": "Add at least one report-driving source (Patreon, Substack, or YouTube) to run a combined report.",
  "business_metrics_rule": "Reports are strongest when the staged workspace snapshot includes direct revenue or subscriber data.",
  "platforms": [
    {
      "platform": "patreon",
      "label": "Patreon",
      "descriptor": "Membership revenue",
      "accepted_file_types_label": "Normalized CSV only",
      "upload_help_text": "Upload the supported Patreon normalized CSV template for this platform.",
      "public_support_status": "supported_now",
      "report_role": "report_driving",
      "standalone_report_eligible": true,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv"
      ],
      "public_contract_ids": [
        "patreon_normalized_csv"
      ],
      "data_domains": [
        "revenue",
        "subscribers"
      ],
      "role_summary": "Revenue and subscriber data. Can generate a report on its own.",
      "known_limitations": [
        "Exact normalized CSV template only",
        "Not every Patreon export CSV matches this contract"
      ]
    },
    {
      "platform": "substack",
      "label": "Substack",
      "descriptor": "Subscription revenue",
      "accepted_file_types_label": "Normalized CSV only",
      "upload_help_text": "Upload the supported Substack normalized CSV template for this platform.",
      "public_support_status": "supported_now",
      "report_role": "report_driving",
      "standalone_report_eligible": true,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv"
      ],
      "public_contract_ids": [
        "substack_normalized_csv"
      ],
      "data_domains": [
        "revenue",
        "subscribers"
      ],
      "role_summary": "Revenue and subscriber data. Can generate a report on its own.",
      "known_limitations": [
        "Exact normalized CSV template only",
        "Not every Substack export CSV matches this contract"
      ]
    },
    {
      "platform": "youtube",
      "label": "YouTube",
      "descriptor": "Revenue and content performance",
      "accepted_file_types_label": "Normalized CSV or YouTube Studio content analytics ZIP",
      "upload_help_text": "Upload the supported YouTube normalized CSV template, or a YouTube Studio content analytics ZIP. To export from YouTube Studio: go to Analytics → Advanced mode → Export → Download as ZIP. The ZIP must contain Table data.csv, Chart data.csv, and Totals.csv. Google Takeout ZIPs are not supported.",
      "public_support_status": "supported_now",
      "report_role": "report_driving",
      "standalone_report_eligible": true,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv",
        ".zip"
      ],
      "public_contract_ids": [
        "youtube_normalized_csv",
        "youtube_studio_zip"
      ],
      "data_domains": [
        "revenue",
        "subscribers",
        "performance"
      ],
      "role_summary": "Can generate a report. Revenue and subscriber depth depends on the YouTube file you upload.",
      "known_limitations": [
        "Exact normalized CSV template only",
        "Not every YouTube CSV export matches this contract",
        "Exact YouTube Studio ZIP shape only",
        "ZIP must contain Table data.csv, Chart data.csv, and Totals.csv",
        "Google Takeout ZIPs are not supported",
        "Revenue and subscriber depth depends on the exported YouTube Studio columns"
      ]
    },
    {
      "platform": "instagram",
      "label": "Instagram",
      "descriptor": "Social performance",
      "accepted_file_types_label": "Normalized CSV or exact allowlisted Instagram ZIP",
      "upload_help_text": "Upload either the supported Instagram normalized CSV template or the exact allowlisted Instagram data export ZIP. To export: go to Instagram Settings → Your activity → Download your information → select JSON format. MVP extraction requires logged_information/past_instagram_insights/posts.json, profiles_reached.json, audience_insights.json, and content_interactions.json. Optional connections/followers_and_following data is used when present; unrelated folders are ignored safely.",
      "public_support_status": "supported_now",
      "report_role": "supporting",
      "standalone_report_eligible": false,
      "business_metrics_capable": false,
      "accepted_extensions": [
        ".csv",
        ".zip"
      ],
      "public_contract_ids": [
        "instagram_allowlisted_zip",
        "instagram_performance_monthly_csv"
      ],
      "data_domains": [
        "performance"
      ],
      "role_summary": "Performance data only. Supports a combined report but cannot generate one alone.",
      "known_limitations": [
        "Exact allowlisted ZIP shape only",
        "Generic Instagram archives and partial shards are rejected",
        "No revenue semantics",
        "Normalized monthly CSV only",
        "Only the allowlisted Instagram ZIP format is supported alongside this CSV fallback"
      ]
    },
    {
      "platform": "tiktok",
      "label": "TikTok",
      "descriptor": "Social performance",
      "accepted_file_types_label": "Normalized CSV or exact allowlisted ZIP",
      "upload_help_text": "Upload either the supported TikTok normalized CSV template or one of the supported native TikTok ZIP exports: Followers, Viewers, or Overview. Only those exact ZIP structures are supported. The Content ZIP is not supported.",
      "public_support_status": "supported_now",
      "report_role": "supporting",
      "standalone_report_eligible": false,
      "business_metrics_capable": false,
      "accepted_extensions": [
        ".csv",
        ".zip"
      ],
      "public_contract_ids": [
        "tiktok_allowlisted_zip",
        "tiktok_performance_monthly_csv"
      ],
      "data_domains": [
        "performance"
      ],
      "role_summary": "Performance data only. Supports a combined report but cannot generate one alone.",
      "known_limitations": [
        "Exact allowlisted TikTok ZIP shapes only",
        "Only the Followers, Viewers, and Overview native exports are accepted",
        "The Content ZIP is not supported",
        "Generic TikTok archives, extra files, and partial shards are rejected",
        "No revenue semantics",
        "Normalized monthly CSV only",
        "Only the allowlisted TikTok ZIP format is supported alongside this CSV fallback"
      ]
    },
    {
      "platform": "other",
      "label": "Additional Income",
      "descriptor": "Sponsorships & brand deals",
      "accepted_file_types_label": "EarnSigma sponsorship CSV template",
      "upload_help_text": "Download and fill in the EarnSigma sponsorship template with your brand deal and sponsorship income, then upload it here.",
      "public_support_status": "supported_now",
      "report_role": "supporting",
      "standalone_report_eligible": false,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv"
      ],
      "public_contract_ids": [
        "sponsorship_rollup_csv"
      ],
      "data_domains": [
        "revenue"
      ],
      "role_summary": "Brand deal and sponsorship income. Blended into total revenue in your report.",
      "known_limitations": [
        "CSV template only — use the EarnSigma sponsorship template",
        "Only paid and delivered deals are counted as confirmed income",
        "Cannot generate a standalone report"
      ]
    }
  ]
};
