import type { SourceManifestResponse } from "../api/upload";

// Generated by `scripts/generate-source-manifest-static.mjs` from
// `creator_optimizer.workspace_data_sources.build_source_manifest_payload()`.
// Do not hand-edit this file.
export const STATIC_SOURCE_MANIFEST_RESPONSE: SourceManifestResponse = {
  "version": 1,
  "eligibility_rule": "Add at least one report-driving source (Patreon, Substack, or YouTube) to run a combined report.",
  "business_metrics_rule": "Reports are strongest when the staged workspace snapshot includes direct revenue or subscriber data.",
  "platforms": [
    {
      "platform": "patreon",
      "label": "Patreon",
      "descriptor": "Membership revenue",
      "accepted_file_types_label": "Normalized CSV only",
      "upload_help_text": "Upload the supported Patreon normalized CSV template for this platform.",
      "public_support_status": "supported_now",
      "report_role": "report_driving",
      "standalone_report_eligible": true,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv"
      ],
      "public_contract_ids": [
        "patreon_normalized_csv"
      ],
      "data_domains": [
        "revenue",
        "subscribers"
      ],
      "role_summary": "Revenue and subscriber data. Can generate a report on its own.",
      "known_limitations": [
        "Exact normalized CSV template only",
        "Not every Patreon export CSV matches this contract"
      ]
    },
    {
      "platform": "substack",
      "label": "Substack",
      "descriptor": "Subscription revenue",
      "accepted_file_types_label": "Normalized CSV only",
      "upload_help_text": "Upload the supported Substack normalized CSV template for this platform.",
      "public_support_status": "supported_now",
      "report_role": "report_driving",
      "standalone_report_eligible": true,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv"
      ],
      "public_contract_ids": [
        "substack_normalized_csv"
      ],
      "data_domains": [
        "revenue",
        "subscribers"
      ],
      "role_summary": "Revenue and subscriber data. Can generate a report on its own.",
      "known_limitations": [
        "Exact normalized CSV template only",
        "Not every Substack export CSV matches this contract"
      ]
    },
    {
      "platform": "youtube",
      "label": "YouTube",
      "descriptor": "Creator earnings",
      "accepted_file_types_label": "Normalized CSV or YouTube Takeout ZIP",
      "upload_help_text": "Upload the supported YouTube normalized CSV template, or a Google Takeout ZIP containing YouTube watch history (Takeout/YouTube and YouTube Music/ folder structure).",
      "public_support_status": "supported_now",
      "report_role": "report_driving",
      "standalone_report_eligible": true,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv",
        ".zip"
      ],
      "public_contract_ids": [
        "youtube_normalized_csv"
      ],
      "data_domains": [
        "revenue",
        "subscribers"
      ],
      "role_summary": "Can generate a report. Revenue and subscriber depth depends on the YouTube file you upload.",
      "known_limitations": [
        "Exact normalized CSV template only",
        "Not every YouTube CSV export matches this contract"
      ]
    },
    {
      "platform": "instagram",
      "label": "Instagram",
      "descriptor": "Social performance",
      "accepted_file_types_label": "Normalized CSV or exact allowlisted ZIP",
      "upload_help_text": "Upload either the supported Instagram normalized CSV template or the supported Instagram export ZIP in the exact allowed format. Not all Instagram ZIP exports are supported.",
      "public_support_status": "supported_now",
      "report_role": "supporting",
      "standalone_report_eligible": false,
      "business_metrics_capable": false,
      "accepted_extensions": [
        ".csv",
        ".zip"
      ],
      "public_contract_ids": [
        "instagram_allowlisted_zip",
        "instagram_performance_monthly_csv"
      ],
      "data_domains": [
        "performance"
      ],
      "role_summary": "Performance data only. Supports a combined report but cannot generate one alone.",
      "known_limitations": [
        "Exact allowlisted ZIP shape only",
        "Generic Instagram archives and partial shards are rejected",
        "No revenue semantics",
        "Normalized monthly CSV only",
        "Only the allowlisted Instagram ZIP format is supported alongside this CSV fallback"
      ]
    },
    {
      "platform": "tiktok",
      "label": "TikTok",
      "descriptor": "Social performance",
      "accepted_file_types_label": "Normalized CSV or exact allowlisted ZIP",
      "upload_help_text": "Upload either the supported TikTok normalized CSV template or the supported TikTok export ZIP in the exact allowed format. Not all TikTok ZIP exports are supported.",
      "public_support_status": "supported_now",
      "report_role": "supporting",
      "standalone_report_eligible": false,
      "business_metrics_capable": false,
      "accepted_extensions": [
        ".csv",
        ".zip"
      ],
      "public_contract_ids": [
        "tiktok_allowlisted_zip",
        "tiktok_performance_monthly_csv"
      ],
      "data_domains": [
        "performance"
      ],
      "role_summary": "Performance data only. Supports a combined report but cannot generate one alone.",
      "known_limitations": [
        "Exact allowlisted ZIP shape only",
        "Generic TikTok archives and partial shards are rejected",
        "No revenue semantics",
        "Normalized monthly CSV only",
        "Only the allowlisted TikTok ZIP format is supported alongside this CSV fallback"
      ]
    }
  ]
};
