import type { SourceManifestResponse } from "../api/upload";

// Generated by `scripts/generate-source-manifest-static.mjs` from
// `creator_optimizer.workspace_data_sources.build_source_manifest_payload()`.
// Do not hand-edit this file.
export const STATIC_SOURCE_MANIFEST_RESPONSE: SourceManifestResponse = {
  "version": 1,
  "eligibility_rule": "Add at least one report-driving source (Patreon, Substack, or YouTube) to run a combined report.",
  "business_metrics_rule": "Reports are strongest when the staged workspace snapshot includes direct revenue or subscriber data.",
  "platforms": [
    {
      "platform": "patreon",
      "label": "Patreon",
      "descriptor": "Membership revenue",
      "accepted_file_types_label": "Normalized CSV only",
      "upload_help_text": "Upload the supported Patreon normalized CSV template for this platform.",
      "public_support_status": "supported_now",
      "report_role": "report_driving",
      "standalone_report_eligible": true,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv"
      ],
      "public_contract_ids": [
        "patreon_normalized_csv"
      ],
      "data_domains": [
        "revenue",
        "subscribers"
      ],
      "role_summary": "Revenue and subscriber data. Can generate a report on its own.",
      "known_limitations": [
        "Exact normalized CSV template only",
        "Not every Patreon export CSV matches this contract"
      ]
    },
    {
      "platform": "substack",
      "label": "Substack",
      "descriptor": "Subscription revenue",
      "accepted_file_types_label": "Normalized CSV only",
      "upload_help_text": "Upload the supported Substack normalized CSV template for this platform.",
      "public_support_status": "supported_now",
      "report_role": "report_driving",
      "standalone_report_eligible": true,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv"
      ],
      "public_contract_ids": [
        "substack_normalized_csv"
      ],
      "data_domains": [
        "revenue",
        "subscribers"
      ],
      "role_summary": "Revenue and subscriber data. Can generate a report on its own.",
      "known_limitations": [
        "Exact normalized CSV template only",
        "Not every Substack export CSV matches this contract"
      ]
    },
    {
      "platform": "youtube",
      "label": "YouTube",
      "descriptor": "Revenue and content performance",
      "accepted_file_types_label": "Normalized CSV or YouTube Studio content analytics ZIP",
      "upload_help_text": "Upload the supported YouTube normalized CSV template, or a YouTube Studio content analytics ZIP. To export from YouTube Studio: go to Analytics → Advanced mode → Export → Download as ZIP. The ZIP must contain Table data.csv, Chart data.csv, and Totals.csv. Google Takeout ZIPs are not supported.",
      "public_support_status": "supported_now",
      "report_role": "report_driving",
      "standalone_report_eligible": true,
      "business_metrics_capable": true,
      "accepted_extensions": [
        ".csv",
        ".zip"
      ],
      "public_contract_ids": [
        "youtube_normalized_csv",
        "youtube_studio_zip"
      ],
      "data_domains": [
        "revenue",
        "subscribers"
      ],
      "role_summary": "Can generate a report. Revenue and subscriber depth depends on the YouTube file you upload.",
      "known_limitations": [
        "Exact normalized CSV template only",
        "Not every YouTube CSV export matches this contract",
        "YouTube Studio ZIP must contain Table data.csv, Chart data.csv, and Totals.csv",
        "Google Takeout ZIPs are not supported"
      ]
    },
    {
      "platform": "instagram",
      "label": "Instagram",
      "descriptor": "Social performance",
      "accepted_file_types_label": "Normalized CSV or native Instagram export ZIP",
      "upload_help_text": "Upload either the supported Instagram normalized CSV template or your native Instagram data export ZIP (downloaded from Instagram Settings → Your activity → Download your information). Only the connections/ and logged_information/ folders are used.",
      "public_support_status": "supported_now",
      "report_role": "supporting",
      "standalone_report_eligible": false,
      "business_metrics_capable": false,
      "accepted_extensions": [
        ".csv",
        ".zip"
      ],
      "public_contract_ids": [
        "instagram_allowlisted_zip",
        "instagram_performance_monthly_csv"
      ],
      "data_domains": [
        "performance"
      ],
      "role_summary": "Used for growth insights and included in combined reports. Cannot generate a report on its own.",
      "known_limitations": [
        "Exact allowlisted ZIP shape only",
        "Generic Instagram archives and partial shards are rejected",
        "No revenue semantics",
        "Normalized monthly CSV only",
        "Only the allowlisted Instagram ZIP format is supported alongside this CSV fallback"
      ]
    },
    {
      "platform": "tiktok",
      "label": "TikTok",
      "descriptor": "Social performance",
      "accepted_file_types_label": "Normalized CSV or native TikTok analytics ZIP",
      "upload_help_text": "Upload either the supported TikTok normalized CSV template or one of the supported native TikTok analytics ZIPs: Followers, Viewers, or Overview. Export from TikTok Studio → Analytics → Export data. The Content ZIP is not supported.",
      "public_support_status": "supported_now",
      "report_role": "supporting",
      "standalone_report_eligible": false,
      "business_metrics_capable": false,
      "accepted_extensions": [
        ".csv",
        ".zip"
      ],
      "public_contract_ids": [
        "tiktok_allowlisted_zip",
        "tiktok_performance_monthly_csv"
      ],
      "data_domains": [
        "performance"
      ],
      "role_summary": "Used for growth insights and included in combined reports. Cannot generate a report on its own.",
      "known_limitations": [
        "Exact allowlisted ZIP shape only",
        "Generic TikTok archives and partial shards are rejected",
        "No revenue semantics",
        "Normalized monthly CSV only",
        "Only the allowlisted TikTok ZIP format is supported alongside this CSV fallback"
      ]
    }
  ]
};
